### ISSUE TITLE
обновить верстку компонента Navbar чтобы соответствовала макету дизайнеров

### ISSUE THREAD

**Issue by uyriq** [FirstLiners/Frontend#10]

**Comment by MVStepanova** [comment]
[Ссылка на макет](https://www.figma.com/file/pIe6rz0bSL9B6WO0VqAa0O/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0-%E2%84%9618-%2F-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%9B%D0%B5%D0%BD%D1%82%D0%B0?type=design&node-id=0-1&mode=design&t=SzedXUKH5MJtvdbU-0)

На всех страницах авторизованный пользователь видит шапку, содержащую кнопки для перехода на страницы разделов: Главная, Данные прогноза, Статистика.
