### ISSUE TITLE
Авторизация фронт верстка

### ISSUE THREAD

**Issue by MVStepanova** [FirstLiners/Frontend#12]

**Comment by MVStepanova** [comment]
[Ссылка на макет](https://www.figma.com/file/pIe6rz0bSL9B6WO0VqAa0O/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0-%E2%84%9618-%2F-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82-%D0%9B%D0%B5%D0%BD%D1%82%D0%B0?type=design&node-id=0-1&mode=design&t=SzedXUKH5MJtvdbU-0)

- [x] - [ ] Создание шаблона страницы авторизации 
- [x] Добавление в форму авторизации поля Логин и Пароль
- [x] Добавление в форму авторизации кнопки Войти
- [x] Создание шаблона сообщения, выпадающего при вводе в форму авторизации некорректного логина и/или пароля
- [x] Создание логики, обеспечивающей авторизацию пользователя в случае введения в форму авторизации корректных логина и пароля
- [x] Лишение авторизованного пользователя прав видеть кнопку Войти
- [x] Добавление на шаблон шапки страницы кнопки Выйти
- [x] Предоставление прав взаимодействия с кнопкой Выйти только авторизованным пользователям

**Comment by uyriq** [comment]
- [x] сделано
